project_name: chirpstack-packet-multiplexer

builds:
  - main: cmd/chirpstack-packet-multiplexer/main.go
    binary: chirpstack-packet-multiplexer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpm:
  vendor: ChirpStack
  homepage: https://www.chirpstack.io/
  maintainer: Orne Brocaar <info@brocaar.com>
  description: ChirpStack Packet Multiplexer
  license: MIT
  formats:
    - deb
  bindir: /usr/bin
  files:
    "packaging/files/chirpstack-packet-multiplexer.rotate": "/etc/logrotate.d/chirpstack-packet-multiplexer"
    "packaging/files/chirpstack-packet-multiplexer.init": "/usr/lib/chirpstack-packet-multiplexer/scripts/chirpstack-packet-multiplexer.init"
    "packaging/files/chirpstack-packet-multiplexer.service": "/usr/lib/chirpstack-packet-multiplexer/scripts/chirpstack-packet-multiplexer.service"
  scripts:
    preinstall: "packaging/scripts/pre-install.sh"
    postinstall: "packaging/scripts/post-install.sh"
    postremove: "packaging/scripts/post-remove.sh"
